name: Deploy to Cloud Run using Docker Hub

on:
  push:
    branches:
      - main  # Deploy only when code is pushed to `main`

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and Push Docker Image to Docker Hub
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/vision-ai:$IMAGE_TAG .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/vision-ai:$IMAGE_TAG

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Debug Base64 Credentials
        run: echo "${{ secrets.CREDENTIALS_JSON }}" | base64 --decode | jq .
    
      - name: Ensure Base64 Encoding (If Needed)
        run: echo "${{ secrets.CREDENTIALS_JSON }}" | base64 > credentials.b64
    
      - name: Deploy to Cloud Run 
        run: |
          gcloud run deploy invoice-scraper \
            --image docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/vision-ai:${{ github.sha }} \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --quiet \
            --timeout=300 \
            --port 8080 \
            --set-env-vars GOOGLE_APPLICATION_CREDENTIALS_BASE64="${{ secrets.CREDENTIALS_JSON }}",SHEET_ID="${{ secrets.SHEET_ID }}"
